app:
  title: PlatformIQ Backsage Application
  baseUrl: http://localhost:3000

organization:
  name: PlatformIQ

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  auth:
    externalAccess:
      - type: static
        options:
          token: ${BACKEND_SECRET}
          subject: api-client

  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: pg
    connection:
      host: ${DB_HOST}       
      port: 5432            
      user: ${DB_USER}        
      password: ${DB_PASS}
  reading:
    allow:
      - host: 'raw.githubusercontent.com'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

# login section for - guest/SSO.
auth:
  #environment: development
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    #guest: {}
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        #lifespan of user session
        sessionDuration: { hours: 24 } # supports `ms` library format (e.g. '24h', '2 days'), ISO duration, "human duration" as used in code
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers
            - resolver: usernameMatchingUserEntityName

catalog:
  providers:
    github:
      components:
        organization: 'Vinay-Venkatesh'
        catalogPath: '**/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
        schedule:
          frequency: PT5M   # Poll every 5 minute
          timeout:   PT5M   # Timeout if it takes more than 5 minutes
      templates:
        organization: 'Vinay-Venkatesh'
        catalogPath: 'templates/bootstrap.yaml'
        filters:
          branch:     'main'
          repository: 'devx-backstage'
        schedule:
          frequency: PT15M   # Poll every 15 minute
          timeout:   PT5M   # Timeout if it takes more than 5 minutes        

  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    # - type: file
    #   target: ../../examples/entities.yaml
      
    # # Local example template
    # - type: file
    #   target: ../../examples/template/template.yaml
    #   rules:
    #     - allow: [Template]

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
    
    # - type: github
    #   target: https://github.com/Vinay-Venkatesh/idp-templates/tree/main/entities
    #   rules:
    #     - allow: [User, Group]

    - type: url
      target: https://raw.githubusercontent.com/Vinay-Venkatesh/idp-templates/main/entities/org.yaml
      rules:
        - allow: [User, Group]

  # Experimental: Always use the search method in UrlReaderProcessor.
  # New adopters are encouraged to enable it as this behavior will be the default in a future release.
  useUrlReadersSearch: true

permission:
  # setting this to `false` will disable permissions
  enabled: true